version: "3.9"
services:

  assem:
    build: ./assem
    ports:
      - "8090:8080"
    volumes:
      - type: volume
        source: outputfile
        target: /tmp/warnik

  prod:
    image: jeanblanchard/tomcat:9
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: outputfile
        target: /opt/tomcat/webapps

volumes:
  outputfile:

